// import 'dart:convert' show utf8;
import 'package:cryptography/cryptography.dart';

import './constants.dart';
// import './exceptions.dart';
// import './util.dart';

class Challenge {
  final List<int> ephemeralServerPublicKey;
  final List<int> salt;

  Challenge({required this.ephemeralServerPublicKey, required this.salt});
}

class Server {
  /// User identifier.
  final String userId;
  /// Salt provided by user during registration.
  final List<int> salt;
  /// Verifier key provided by user during registration.
  final List<int> verifierKey;
  /// Ephemeral public user key generated by user to initiate a session.
  final List<int> ephemeralUserPublicKey;
  /// A generator modulo N.
  /// Typically denoted 'g'.
  final BigInt generator;
  /// Hash algorithm used during SRP key and verifier calculations (e.g., SHA256).
  final HashAlgorithm hashAlgorithm;
  /// A large, safe prime.
  /// Typically denoted 'N'.
  /// By definition a safe prime N = 2q + 1, where q is a Sophie Germain prime.
  /// All arithmetic is performed in the field of integers modulo N.
  final BigInt safePrime;

  List<int>? ephemeralServerPrivateKey;
  List<int>? ephemeralServerPublicKey;

  Server({
      required this.userId,
      required this.salt,
      required this.verifierKey,
      required this.ephemeralUserPublicKey,
      BigInt? generator,
      BigInt? safePrime,
      HashAlgorithm? hashAlgorithm,
  }) : generator = generator ?? BigInt.from(2),
       safePrime = safePrime ?? defaultSafePrime,
       hashAlgorithm = hashAlgorithm ?? defaultHashAlgorithm;

  // Challenge createChallenge() {
  //   // B = kv + g^b
  //   ephemeralServerPublicKey = ;
  //   return Challenge(
  //     ephemeralServerPublicKey: ephemeralServerPublicKey,
  //     salt: salt,
  //   );
  // }
}
