import 'dart:convert' show utf8;
import 'package:cryptography/cryptography.dart';

import 'defaults.dart' show defaultHashAlgorithm, defaultSafePrime;
import 'exceptions.dart' show AuthenticationFailure;
import 'rfc5054.dart';
import 'util.dart';

/// Challenge server offers to the user to verify their identity.
///
/// This provides the user the minimum data needed from the server to generate
/// the session key and its verifier.
class Challenge {
  final List<int> ephemeralServerPublicKey;
  final List<int> salt;

  Challenge({required this.ephemeralServerPublicKey, required this.salt});
}

/// Operations the server / host performs to authenticate a user via SRP.
class Server {
  /// User identifier.
  final String userId;
  /// Salt provided by user during registration.
  final List<int> salt;
  /// Verifier key provided by user during registration.
  final BigInt verifierKey;
  /// Ephemeral public user key generated by user to initiate a session.
  final List<int> ephemeralUserPublicKey;
  /// A generator modulo N.
  /// Typically denoted 'g'.
  final BigInt generator;
  /// Hash algorithm used during SRP key and verifier calculations (e.g., SHA256).
  final HashAlgorithm hashAlgorithm;
  /// A large, safe prime.
  /// Typically denoted 'N'.
  /// By definition a safe prime N = 2q + 1, where q is a Sophie Germain prime.
  /// All arithmetic is performed in the field of integers modulo N.
  final BigInt safePrime;

  BigInt? serverPrivateKey;
  BigInt? serverPublicKey;
  List<int>? sessionKey;

  Server({
      required this.userId,
      required this.salt,
      required List<int> verifierKey,
      required this.ephemeralUserPublicKey,
      BigInt? generator,
      BigInt? safePrime,
      HashAlgorithm? hashAlgorithm,
  }) : verifierKey = verifierKey.toBigInt(),
       generator = generator ?? BigInt.from(2),
       safePrime = safePrime ?? defaultSafePrime,
       hashAlgorithm = hashAlgorithm ?? defaultHashAlgorithm;

  /// Create verification challenge to send to user.
  Future<Challenge> createChallenge({List<int>? serverPrivateKeyBytes}) async {
    serverPrivateKeyBytes ??= generateRandomBytes(32);
    serverPrivateKey = serverPrivateKeyBytes.toBigInt();
    // k = H(N,g)
    final multiplierParameter = (await _hashRfc5054(
        [safePrime.toByteList(), generator.toByteList()]
    )).toBigInt();
    // B = kv + g^b
    serverPublicKey = (multiplierParameter * verifierKey + generator.modPow(serverPrivateKey!, safePrime)) % safePrime;
    return Challenge(
      ephemeralServerPublicKey: serverPublicKey!.toByteList(),
      salt: salt,
    );
  }

  /// Verify that session key generated by user is the same as the one generated by server.
  ///
  /// Returns a server-generated session key verifier the user can use to verify
  /// the server's identity.
  Future<List<int>> verifySession(List<int> userSessionKeyVerifier) async {
    sessionKey = await _deriveSessionKey();
    /// Verify user session key.
    final expectedUserSessionKeyVerifier = await _deriveUserSessionKeyVerifier();
    if (!expectedUserSessionKeyVerifier.equals(userSessionKeyVerifier)) {
      throw AuthenticationFailure('User session key failed verification.');
    }
    /// Create server verifier key.
    // M2 = H(A, M, K)
    final serverSessionKeyVerifier = (await hashAlgorithm.hash(
        ephemeralUserPublicKey + userSessionKeyVerifier + sessionKey!
    )).bytes;
    return serverSessionKeyVerifier;
  }

  Future<List<int>> _deriveSessionKey() async {
    // u = H(A,B)
    final randomScramblingParameter = (await _hashRfc5054(
        [ephemeralUserPublicKey, serverPublicKey!.toByteList()]
    )).toBigInt();
    // Av^u
    final innerTerm = ephemeralUserPublicKey.toBigInt() *
        verifierKey.modPow(randomScramblingParameter, safePrime);
    // K = H((Av^u) ^ b)
    final sessionKey = (await hashAlgorithm.hash((innerTerm.modPow(serverPrivateKey!, safePrime)).toByteList())).bytes;
    return sessionKey;
  }

  //TODO: Merge with User.processChallenge.
  // M1 = H(H(N) xor H(g), H(I), s, A, B, K)
  Future<List<int>> _deriveUserSessionKeyVerifier() async {
    // H(N)
    final hashedSafePrime = (await hashAlgorithm.hash(safePrime.toByteList())).bytes.toBigInt();
    // H(g)
    final hashedGenerator = (await _hashRfc5054([generator.toByteList()])).toBigInt();
    // H(I)
    final hashedUserId = (await hashAlgorithm.hash(utf8.encode(userId))).bytes;
    // H(N) xor H(g)
    final hashedSafePrimeAndGenerator = (hashedSafePrime ^ hashedGenerator).toByteList();
    final sessionKeyVerifier = (await hashAlgorithm.hash(
        hashedSafePrimeAndGenerator +
        hashedUserId +
        salt +
        ephemeralUserPublicKey +
        serverPublicKey!.toByteList() +
        sessionKey!
    )).bytes;
    return sessionKeyVerifier;
  }

  Future<List<int>> _hashRfc5054(List<List<int>> byteLists) async {
    //OPTIMIZE: Make this a class field.
    final safePrimeBytes = safePrime.toByteList();
    return hashRfc5054(
      byteLists: byteLists,
      safePrime: safePrimeBytes,
      hashAlgorithm: hashAlgorithm
    );
  }
}
