import 'dart:convert' show utf8;
import 'package:cryptography/cryptography.dart' show HashAlgorithm;
import 'package:dsrp/defaults.dart' show defaultByteLengthForEphemeralKeys, defaultGenerator, defaultHashAlgorithmChoice, defaultSafePrime;
import 'package:dsrp/exceptions.dart' show AuthenticationFailure;
import 'package:dsrp/hash.dart';
import 'package:dsrp/rfc5054.dart';
import 'package:dsrp/util.dart';
import 'package:logging/logging.dart';

final _log = Logger('dsrp.Server');

/// Challenge server offers to the user to verify their identity.
///
/// This provides the user the minimum data needed from the server to generate
/// the session key and its verifier.
class Challenge {
  final int generator;
  final List<int> safePrime;
  final List<int> ephemeralServerPublicKey;
  final List<int> verifierKeySalt;
  final HashAlgorithmChoice hashAlgorithm;

  Challenge({
      required this.generator,
      required this.safePrime,
      required this.ephemeralServerPublicKey,
      required this.verifierKeySalt,
      required this.hashAlgorithm
  });
}

/// Operations the server / host performs to authenticate a user via SRP.
///
/// Designed to mimic the API of Python's pysrp library.
class Server {
  /// User identifier.
  final String userId;
  /// Salt provided by user during registration.
  final List<int> salt;
  /// Verifier key provided by user during registration.
  final BigInt verifierKey;
  /// A generator modulo N.
  /// Typically denoted 'g'.
  final BigInt generator;
  /// Hash algorithm used during SRP key and verifier calculations (e.g., SHA256).
  final HashAlgorithmChoice hashAlgorithmChoice;
  /// Hash algorithm used during SRP key and verifier calculations (e.g., SHA256).
  final HashAlgorithm hashAlgorithm;
  /// A large, safe prime.
  /// Typically denoted 'N'.
  /// By definition a safe prime N = 2q + 1, where q is a Sophie Germain prime.
  /// All arithmetic is performed in the field of integers modulo N.
  final BigInt safePrime;

  BigInt? ephemeralServerPrivateKey;
  List<int>? ephemeralServerPublicKey;
  List<int>? sessionKey;

  Server({
      required this.userId,
      required this.salt,
      required List<int> verifierKey,
      BigInt? generator,
      List<int>? safePrime,
      HashAlgorithmChoice? hashAlgorithm,
  }) : verifierKey = verifierKey.toBigInt(),
       generator = generator ?? defaultGenerator,
       safePrime = safePrime?.toBigInt() ?? defaultSafePrime,
       hashAlgorithmChoice = hashAlgorithm ?? defaultHashAlgorithmChoice,
       hashAlgorithm = getHashAlgorithm(hashAlgorithm ?? defaultHashAlgorithmChoice) {
    if (safePrime == null) {
      _log.warning('Using default safe prime. For production use, generate a custom safe prime using scripts/generate_safe_primes to reduce risk of pre-computed attacks.');
    }
  }

  /// Create verification challenge to send to user.
  Future<Challenge> createChallenge({List<int>? ephemeralServerPrivateKeyBytes}) async {
    ephemeralServerPrivateKeyBytes ??= generateRandomBytes(defaultByteLengthForEphemeralKeys);
    ephemeralServerPrivateKey = ephemeralServerPrivateKeyBytes.toBigInt();
    // k = H(N,g)
    final multiplierParameter = (await _hashRfc5054(
        [safePrime.toByteList(), generator.toByteList()]
    )).toBigInt();
    // B = kv + g^b
    final ephemeralServerPublicKeyInt = (multiplierParameter * verifierKey + generator.modPow(ephemeralServerPrivateKey!, safePrime)) % safePrime;
    ephemeralServerPublicKey = ephemeralServerPublicKeyInt.toByteList();
    return Challenge(
      generator: generator.toInt(),
      safePrime: safePrime.toByteList(),
      ephemeralServerPublicKey: ephemeralServerPublicKey!,
      verifierKeySalt: salt,
      hashAlgorithm: hashAlgorithmChoice
    );
  }

  /// Derive session key from user public key.
  ///
  /// NOTE: This should only be called if your SRP usage involves decrypting the user session key verifier using the session key. Regardless, you still need to verify the session key before considering the session verified.
  Future<List<int>> deriveSessionKey({required List<int> ephemeralUserPublicKey}) async {
    if (ephemeralUserPublicKey.toBigInt() % safePrime == BigInt.zero) {
      throw AuthenticationFailure('Invalid ephemeral user public key.');
    }
    // u = H(A,B)
    final randomScramblingParameter = (await _hashRfc5054(
        [ephemeralUserPublicKey, ephemeralServerPublicKey!]
    )).toBigInt();
    // Av^u
    final base = ephemeralUserPublicKey.toBigInt() * verifierKey.modPow(randomScramblingParameter, safePrime);
    // (Av^u) ^ b
    final power = base.modPow(ephemeralServerPrivateKey!, safePrime).toByteList();
    // K = H((Av^u) ^ b)
    sessionKey = (await hashAlgorithm.hash(power)).bytes;
    return sessionKey!;
  }

  /// Verify that session key generated by user is the same as the one generated by server.
  ///
  /// Returns a server-generated session key verifier the user can use to verify
  /// the server's identity.
  Future<List<int>> verifySession({
      required List<int> userSessionKeyVerifier, required List<int> ephemeralUserPublicKey
  }) async {
    if (sessionKey == null) {
      await deriveSessionKey(ephemeralUserPublicKey: ephemeralUserPublicKey);
    }
    // Verify user session key.
    final expectedUserSessionKeyVerifier = await _deriveUserSessionKeyVerifier(
      ephemeralUserPublicKey);
    if (!expectedUserSessionKeyVerifier.equals(userSessionKeyVerifier)) {
      throw AuthenticationFailure('User session key failed verification.');
    }
    // Create server verifier key.
    // M2 = H(A, M, K)
    final serverSessionKeyVerifier = (await hashAlgorithm.hash(
        ephemeralUserPublicKey + userSessionKeyVerifier + sessionKey!
    )).bytes;
    return serverSessionKeyVerifier;
  }

  ///TODO: Merge with User.processChallenge?
  /// M1 = H(H(N) xor H(g), H(I), s, A, B, K)
  Future<List<int>> _deriveUserSessionKeyVerifier(List<int> ephemeralUserPublicKey) async {
    // H(N)
    final hashedSafePrime = (await hashAlgorithm.hash(safePrime.toByteList())).bytes.toBigInt();
    // H(g)
    final hashedGenerator = (await _hashRfc5054([generator.toByteList()])).toBigInt();
    // H(I)
    final hashedUserId = (await hashAlgorithm.hash(utf8.encode(userId))).bytes;
    // H(N) xor H(g)
    final hashedSafePrimeAndGenerator = (hashedSafePrime ^ hashedGenerator).toByteList();
    // M1 = H(H(N) xor H(g), H(I), s, A, B, K)
    final sessionKeyVerifier = (await hashAlgorithm.hash(
        hashedSafePrimeAndGenerator +
        hashedUserId +
        salt +
        ephemeralUserPublicKey +
        ephemeralServerPublicKey! +
        sessionKey!
    )).bytes;
    return sessionKeyVerifier;
  }

  Future<List<int>> _hashRfc5054(List<List<int>> byteLists) async {
    //OPTIMIZE: Make this a class field.
    final safePrimeBytes = safePrime.toByteList();
    return hashRfc5054(
      byteLists: byteLists,
      safePrime: safePrimeBytes,
      hashAlgorithm: hashAlgorithm
    );
  }
}
