import 'dart:convert' show utf8;
import 'package:cryptography/cryptography.dart';

import './constants.dart' show defaultHashAlgorithm, defaultSafePrime;
import './exceptions.dart';
import './rfc5054.dart';
import './util.dart';

/// Verification key generated by user on client-side.
/// This data should be registered with the server for future authentication.
class SaltedVerificationKey {
  //OPTIMIZE: Use Uint8List, since int defaults 64-bit rather than a byte?
  final List<int> key;
  final List<int> salt;

  SaltedVerificationKey({required this.key, required this.salt});
}

/// Data to be sent to the server in the request to initiate SRP authentication.
class StartAuthenticationData {
  final String userId;
  final List<int> ephemeralUserPublicKey;

  StartAuthenticationData({required this.userId, required this.ephemeralUserPublicKey});
}

/// Operations the user / client performs to authenticate via SRP.
class User {
  //TODO: Goal here is to mimic pysrp. So probably mimic its API until you get a
  // better sense.

  /// User identifier.
  final String userId;
  /// User password.
  final String password;
  /// A generator modulo N.
  /// Typically denoted 'g'.
  final BigInt generator;
  /// Hash algorithm used during SRP key and verifier calculations (e.g., SHA256).
  @override
  final HashAlgorithm hashAlgorithm;
  /// A large, safe prime.
  /// Typically denoted 'N'.
  /// By definition a safe prime N = 2q + 1, where q is a Sophie Germain prime.
  /// All arithmetic is performed in the field of integers modulo N.
  /// TODO: Generate N. Got this 1024 bit prime from RFC 5054 Appendix A section 1.
  @override
  final BigInt safePrime;

  /// Ephemeral private key generated by user during authentication.
  BigInt? userPrivateKey;
  /// Ephemeral public key generated by user during authentication.
  List<int>? userPublicKeyBytes;
  /// Shared symmetric key used for encrypting messages sent between user and server.
  ///
  /// Derived from the Diffie-Hellman shared secret.
  List<int>? sessionKey;
  /// Used to verify both user and server have derived the same session key.
  List<int>? sessionKeyVerifier;

  User({
    required this.userId,
    required this.password,
    BigInt? generator,
    BigInt? safePrime,
    HashAlgorithm? hashAlgorithm,
  })  : generator = generator ?? BigInt.from(2),
        safePrime = safePrime ?? defaultSafePrime,
        hashAlgorithm = hashAlgorithm ?? defaultHashAlgorithm;

  /// Creates salted verification key.
  ///
  /// Pass this data to server as part of user registration request.
  Future<SaltedVerificationKey> createSaltedVerificationKey({List<int>? salt}) async {
    //TODO: How big should the salt be?
    salt ??= generateRandomBytes(128);
    final privateKey = await _derivePrivateKey(salt);
    final verifierKey = _deriveVerificationKey(privateKey);
    final verifierKeyBytes = verifierKey.toByteList();
    return SaltedVerificationKey(
      key: verifierKeyBytes,
      salt: salt,
    );
  }

  Future<SaltedVerificationKey> createSaltedVerificationKeyWithArgon2() async {
    //TODO: How big should the salt be?
    final salt = List<int>.generate(128, (index) => random.nextInt(256));
    //TODO: Hash alg should be specifiable.
    final argon2id = Argon2id(
      //OPTIMIZE: What should these values be?
      parallelism: 3,
      memorySize: 10000000,
      iterations: 3,
      hashLength: 32,
    );
    // Private key (as defined by RFC 5054)
    // x = H(s, H( I | ‘:’ | p ))
    var privateKey = await argon2id.deriveKey(
      //TODO: How should this secret key be formatted?
      secretKey: SecretKey(utf8.encode('$userId:$password')),
      nonce: [],
    );
    privateKey = await argon2id.deriveKey(
      secretKey: privateKey,
      nonce: salt,
    );
    final privateKeyInt = (await privateKey.extractBytes()).toBigInt();
    final verifierKey = generator.modPow(privateKeyInt, safePrime);
    final verifierKeyBytes = verifierKey.toByteList();
    return SaltedVerificationKey(
      key: verifierKeyBytes,
      salt: salt,
    );
  }

  /// Generates data needed in server request to initiate authentication.
  StartAuthenticationData startAuthentication({List<int>? userPrivateKeyBytes}) {
    userPrivateKeyBytes ??= generateRandomBytes(32);
    userPrivateKey = userPrivateKeyBytes.toBigInt();
    // A = g^a
    final userPublicKey = generator.modPow(userPrivateKey!, safePrime);
    userPublicKeyBytes = userPublicKey.toByteList();
    return StartAuthenticationData(
      userId: userId,
      ephemeralUserPublicKey: userPublicKeyBytes!,
    );
  }

  /// Processes challenge from server.
  ///
  /// Returns session key verifier to be sent to the server so it can verify the user.
  ///
  /// Session key verifier is often denoted 'M' or 'M1'.
  Future<List<int>> processChallenge(
    List<int> salt, List<int> serverPublicKeyBytes
  ) async {
    final sessionKey = await _deriveSessionKey(salt, serverPublicKeyBytes);
    // H(N)
    final hashedSafePrime = (
      await hashAlgorithm.hash(safePrime.toByteList())
    ).bytes.toBigInt();
    // H(g)
    final hashedGenerator = (
      await _hashRfc5054([generator.toByteList()])
    ).toBigInt();
    // H(I)
    final hashedUserId = (await hashAlgorithm.hash(utf8.encode(userId))).bytes;
    // H(N) xor H(g)
    final hashedSafePrimeAndGenerator = (hashedSafePrime ^ hashedGenerator).toByteList();
    // M1 = H(H(N) xor H(g), H(I), s, A, B, K)
    sessionKeyVerifier = (await hashAlgorithm.hash(
        hashedSafePrimeAndGenerator +
        hashedUserId +
        salt +
        userPublicKeyBytes! +
        serverPublicKeyBytes +
        sessionKey)
    ).bytes;
    return sessionKeyVerifier!;
  }

  /// Verify server session key matches expected value, which verifies server is who is expected.
  /// Throws exception if it does not, in which case authentication should be abandoned.
  ///
  /// Server session key verifier is often denoted 'M2' and is provided in the
  /// server response to the client-generated session key verifier M1.
  verifySession(List<int> serverSessionKeyVerifier) async {
    // M2 = H(A, M, K)
    final expectedServerSessionKeyVerifier =
        (await hashAlgorithm.hash(userPublicKeyBytes! + sessionKeyVerifier! + sessionKey!))
            .bytes;
    if (!serverSessionKeyVerifier.equals(expectedServerSessionKeyVerifier)) {
      throw AuthenticationFailure('Server session key does not match expected value.');
    }
  }

  /// Private key (as defined by RFC 5054)
  /// x = H(s, H( I | ‘:’ | p ))
  Future<BigInt> _derivePrivateKey(List<int> salt) async {
    var privateKeyHash = await hashAlgorithm.hash(
        //TODO: How should this be formatted?
        utf8.encode('$userId:$password'));
    privateKeyHash = await hashAlgorithm.hash(salt + privateKeyHash.bytes);
    final privateKey = privateKeyHash.bytes.toBigInt();
    return privateKey;
  }

  /// Password verifier, a.k.a. verification key.
  /// v = g^x
  BigInt _deriveVerificationKey(BigInt privateKey) {
    final saltedVerificationKey = generator.modPow(privateKey, safePrime);
    return saltedVerificationKey;
  }

  /// Calculates the session key which will later be used for encrypted communication with server.
  ///
  /// K = H( (B - kg^x) ^ (a + ux) ) = H( (B - kv) ^ (a + ux) )
  Future<List<int>> _deriveSessionKey(
      List<int> salt, List<int> serverPublicKeyBytes) async {
    // x
    final privateKey = await _derivePrivateKey(salt);
    // v = g^x
    final verifierKey = _deriveVerificationKey(privateKey);
    // u = H(A,B)
    final randomScramblingParameter = (await _hashRfc5054(
        [userPublicKeyBytes!, serverPublicKeyBytes]
    )).toBigInt();
    if (randomScramblingParameter == BigInt.zero) {
      throw 'Abort authentication! Random scrambling parameter (u = H(A,B)) is zero.';
    }
    // k = H(N,g)
    final multiplierParameter = (await _hashRfc5054(
        [safePrime.toByteList(), generator.toByteList()]
    )).toBigInt();
    // Notated 'B'.
    final serverPublicKey = serverPublicKeyBytes.toBigInt();
    if (serverPublicKey % safePrime == BigInt.zero) {
      throw 'Abort authentication! Ephemeral public server key is invalid (B % N == 0).';
    }
    // B - k(g^x) = B - kv
    final firstTerm = serverPublicKey - multiplierParameter * verifierKey;
    // a + ux
    final secondTerm = userPrivateKey! + randomScramblingParameter * privateKey;
    // S = (B - kv) ^ (a + ux)
    final secret = firstTerm.modPow(secondTerm, safePrime);
    // K = H( (B - kg^x) ^ (a + ux) ) = H( (B - kv) ^ (a + ux) ) = H(S)
    sessionKey = (await hashAlgorithm.hash(secret.toByteList())).bytes;
    return sessionKey!;
  }

  Future<List<int>> _hashRfc5054(List<List<int>> byteLists) async {
    //OPTIMIZE: Make this a class field.
    final safePrimeBytes = safePrime.toByteList();
    return hashRfc5054(
      byteLists: byteLists,
      safePrime: safePrimeBytes,
      hashAlgorithm: hashAlgorithm
    );
  }
}
