import 'dart:convert' show utf8;
import 'package:cryptography/cryptography.dart';
import 'package:dsrp/defaults.dart' show defaultGenerator, defaultKdfAlgorithmChoice, defaultSafePrime, defaultSaltByteLengthForSaltedVerificationKey, deriveOptimalByteLengthForEphemeralKeys;
import 'package:dsrp/exceptions.dart' show AuthenticationFailure;
import 'package:dsrp/crypto/hash.dart';
import 'package:dsrp/crypto/kdf.dart';
import 'package:dsrp/rfc5054.dart';
import 'package:dsrp/server.dart' show Challenge;
import 'package:dsrp/util/bytes.dart';
import 'package:dsrp/util/collections.dart';
import 'package:logging/logging.dart';

final _log = Logger('dsrp.User');

/// Verification key generated by user on client-side.
/// This data should be registered with the server for future authentication.
class SaltedVerificationKey {
  //OPTIMIZE: Use Uint8List, since int defaults 64-bit rather than a byte?
  final List<int> key;
  final List<int> salt;

  SaltedVerificationKey({required this.key, required this.salt});

  /// Overwrites sensitive data with zeros.
  void erase() {
    key.overwriteWithZeros();
    salt.overwriteWithZeros();
  }
}

/// Data to be sent to the server to verify the user session key.
class UserSessionVerifiers {
  final String userId;
  final List<int> ephemeralUserPublicKey;
  final List<int> sessionKeyVerifier;

  UserSessionVerifiers({
      required this.userId,
      required this.ephemeralUserPublicKey,
      required this.sessionKeyVerifier
  });

  /// Overwrites sensitive data with zeros.
  void erase() {
    ephemeralUserPublicKey.overwriteWithZeros();
    sessionKeyVerifier.overwriteWithZeros();
  }
}

/// Operations the user / client performs to register and authenticate with a
/// server via SRP.
///
/// Once authentication is complete, store the session key somewhere, then
/// ensure sensitive information in the [User] object is erased by allowing the
/// garbage collector to delete the object (i.e., allow all references to the
/// object to go out of scope and/or be set to null). The object internally
/// attempts to delete data as soon as it is no longer needed.
///
/// Designed to mimic the API of Python's pysrp library.
class User {

  /// User identifier.
  ///
  /// Used to derive the session key verifier, and optionally the user private
  /// key.
  /// 
  /// If the user ID is used to derive the private key, it is recommended to use
  /// a unique ID which does not change when the user-selected username changes.
  /// This avoids having to re-perform SRP user registration when the username
  /// changes.
  String? _userId;
  /// User password.
  ///
  /// Used to derive the user private key.
  ///
  /// To increase the difficulty of attacks on SRP, follow standard secure
  /// password requirements such as those suggested by NIST (e.g., long
  /// passwords that are difficult to guess).
  String? _password;
  /// Hash algorithm used during SRP ephemeral key and verifier calculations (e.g., SHA256).
  final HashAlgorithm _hashAlgorithm;
  /// KDF algorithm used to derive user private key.
  final KdfAlgorithm _kdfAlgorithm;
  /// A generator modulo N (the safe prime).
  /// Typically denoted 'g'.
  final BigInt generator;
  /// A large, safe prime.
  /// Typically denoted 'N'.
  /// By definition a safe prime N = 2q + 1, where q is a Sophie Germain prime.
  /// All arithmetic is performed in the field of integers modulo N.
  final BigInt safePrime;

  /// If true, use user ID along with password in KDF to generate user private
  /// key. Otherwise only the password is used.
  ///
  /// Only using the password avoids the need to regenerate the user private key
  /// if the user ID changes. Alternatively, a unique user ID,
  /// which does not change when the username changes, can be used.
  final bool useUserIdInPrivateKey;

  /// Salt used to generate the user private key when deriving the session key
  /// verifier.
  final List<int> _verifierKeySalt;

  /// Shared symmetric key which can be used for encrypting messages sent
  /// between user and server.
  ///
  /// Derived from the Diffie-Hellman shared secret.
  ///
  /// It is recommended not to directly use this key for encrypting messages,
  /// but instead derive keys from it using, say HKDF, for authentication,
  /// encryption, and integrity.
  ///
  /// Note that SRP can be used purely for authentication and generating a
  /// session token / cookie, and need not be used to encrypt messages if an
  /// already trusted encryption mechanism is being used (e.g., TLS).
  late final List<int> sessionKey;
  /// To be sent to the server so it can verify the user and the user's derived
  /// session key.
  late final List<int> _userSessionKeyVerifier;

  /// Ephemeral asymmetric private key generated by user during authentication and then discarded.
  BigInt? _ephemeralUserPrivateKey;
  /// Ephemeral asymmetric public key generated by user during authentication and then discarded.
  List<int>? _ephemeralUserPublicKeyBytes;

  /// As part of initial user authentication handshake, create a [User] from a
  /// [challenge] provided by the server.
  ///
  /// WARNING: If the server provides the core SRP parameters (safe prime,
  /// generator, hash algorithm) it is highly recommended for the client to
  /// verify they are cryptographically secure. This could include checking the
  /// hash algorithm is one of those expected, and that the safe prime and
  /// generator and secure (see [verifySafePrime] and [verifyGenerator]).
  ///
  /// Enable [useUserIdInPrivateKey] if the user ID was used for key generation
  /// during user registration. See [createSaltedVerificationKey] for details.
  /// If [useUserIdInPrivateKey] is false, the user ID is only used to generate
  /// the user-side verifier.
  ///
  /// If [kdfAlgorithm] is not provided, Argon2id is used since it is slow and
  /// hence relatively secure. Be sure this KDF matches the one used during
  /// registration.
  ///
  /// If a [ephemeralUserPrivateKey] is not provided, one is generated.
  static Future<User> fromUserCredsAndChallenge({
    required String userId,
    required String password,
    required Challenge challenge,
    final bool useUserIdInPrivateKey = true,
    final KdfAlgorithmChoice kdfAlgorithm = defaultKdfAlgorithmChoice,
    final List<int>? ephemeralUserPrivateKey,
  }) async {
    final user = User._(
      userId: userId, password: password,
      generator: BigInt.from(challenge.generator),
      safePrime: challenge.safePrime.toBigInt(),
      verifierKeySalt: challenge.verifierKeySalt,
      useUserIdInPrivateKey: useUserIdInPrivateKey,
      hashAlgorithm: challenge.hashAlgorithm,
      kdfAlgorithm: kdfAlgorithm,
    );
    user._generateEphemeralUserAsymmetricKeys(
      ephemeralUserPrivateKeyBytes: ephemeralUserPrivateKey);
    // Derives session key and its user-side verifier M1.
    await user._processChallenge(challenge);

    //TODO: Securely erase portions of challenge no longer needed. Seems to be
    // immutable, so probably wait for universal switch to Uint8List.
    // challenge.ephemeralServerPublicKey.overwriteWithZeros();

    return user;
  }

  User._({
    required String userId,
    required String password,
    required this.generator,
    required this.safePrime,
    required List<int> verifierKeySalt,
    required this.useUserIdInPrivateKey,
    required HashAlgorithmChoice hashAlgorithm,
    required KdfAlgorithmChoice kdfAlgorithm,
  }): _password = password, _userId = userId, _verifierKeySalt = verifierKeySalt,
    _hashAlgorithm = getHashAlgorithm(hashAlgorithm),
    _kdfAlgorithm = getKdfAlgorithm(kdfAlgorithm);

  /// Creates a salted verification key.
  ///
  /// Pass this key to server as part of user registration request.
  /// 
  /// WARNING: If [safePrime] is not provided, the default safe prime provided
  /// by dsrp is used. This should NOT be done in production. You are encouraged
  /// to generate your own safe prime instead to reduce the chance of a
  /// pre-computed attack on common safe primes impacting your users.
  ///
  /// If [kdfAlgorithm] is not provided, Argon2id is used since it is slow and
  /// hence relatively secure.
  ///
  /// If [salt] is not provided then a 32-byte random salt is generated.
  ///
  /// Only provide [userId] if you want derivation of the user private key to
  /// include it, as is done in the RFC5054 standard. Not including the user ID
  /// means if the ID changes, the user private key will need to be regenerated
  /// and the user registration process repeated. When key derivation excludes
  /// the user ID, re-registration is only needed if the password changes.
  ///
  /// Another option is to provide a unique, fixed [userId] (e.g., a UUID, user
  /// database index, etc.) that is different from the user-chosen ID. That
  /// allows the user to change their login ID while their internal user ID
  /// remains constant.
  static Future<SaltedVerificationKey> createSaltedVerificationKey({
      required String password,
      String? userId,
      int? generator, List<int>? safePrime,
      KdfAlgorithmChoice? kdfAlgorithm,
      List<int>? salt
  }) async {
    final generatorBigInt = generator != null ? BigInt.from(generator) : defaultGenerator;
    final safePrimeBigInt = safePrime?.toBigInt() ?? defaultSafePrime;
    if (safePrime == null) {
      _log.warning('Using default safe prime. For production use, generate a custom safe prime using scripts/generate_safe_primes to reduce risk of pre-computed attacks.');
    }
    final chosenKdfAlgorithm = getKdfAlgorithm(kdfAlgorithm ?? defaultKdfAlgorithmChoice);
    salt ??= generateRandomBytes(defaultSaltByteLengthForSaltedVerificationKey);
    final privateKey = await _derivePrivateKey(userId: userId, password: password,
      salt: salt, kdfAlgorithm: chosenKdfAlgorithm);
    final verifierKey = _deriveVerificationKey(privateKey: privateKey,
      generator: generatorBigInt, safePrime: safePrimeBigInt);
    final verifierKeyBytes = verifierKey.toByteList();
    return SaltedVerificationKey(
      key: verifierKeyBytes,
      salt: salt,
    );
  }

  /// Generates ephemeral user public and private keys which are used only
  /// during SRP login and then discarded.
  _generateEphemeralUserAsymmetricKeys({List<int>? ephemeralUserPrivateKeyBytes}) {
    ephemeralUserPrivateKeyBytes ??= generateRandomBytes(
      deriveOptimalByteLengthForEphemeralKeys(safePrime.bitLength)
    );
    _ephemeralUserPrivateKey = ephemeralUserPrivateKeyBytes.toBigInt();
    // A = g^a
    final publicKey = generator.modPow(_ephemeralUserPrivateKey!, safePrime);
    _ephemeralUserPublicKeyBytes = publicKey.toByteList();
  }

  /// Processes challenge from server, deriving session key and its verifier.
  ///
  /// Session key verifier is often denoted 'M' or 'M1'.
  Future<void> _processChallenge(Challenge challenge) async {
    sessionKey = await _deriveSessionKey(
      challenge.verifierKeySalt,
      challenge.ephemeralServerPublicKey
    );
    // H(N)
    final hashedSafePrime = (
      await _hashAlgorithm.hash(safePrime.toByteList())
    ).bytes.toBigInt();
    // H(g)
    final hashedGenerator = (
      await _hashRfc5054([generator.toByteList()])
    ).toBigInt();
    // H(I)
    final hashedUserId = (await _hashAlgorithm.hash(utf8.encode(_userId!))).bytes;
    // H(N) xor H(g)
    final hashedSafePrimeAndGenerator = (hashedSafePrime ^ hashedGenerator).toByteList();
    // M1 = H(H(N) xor H(g), H(I), s, A, B, K)
    _userSessionKeyVerifier = (await _hashAlgorithm.hash(
        hashedSafePrimeAndGenerator +
        hashedUserId +
        challenge.verifierKeySalt +
        _ephemeralUserPublicKeyBytes! +
        challenge.ephemeralServerPublicKey +
        sessionKey
    )).bytes;
  }

  /// Retrieve user session verifiers to send to server.
  UserSessionVerifiers getUserSessionVerifiers() {
    final verifiers = UserSessionVerifiers(
      userId: _userId!,
      ephemeralUserPublicKey: List.of(_ephemeralUserPublicKeyBytes!),
      sessionKeyVerifier: List.of(_userSessionKeyVerifier),
    );
    _userId = null; // No longer needed, discard immediately.
    return verifiers;
  }

  /// Verify server session key matches expected value, which verifies server is who is expected.
  /// Throws exception if it does not, in which case authentication should be abandoned.
  ///
  /// Server session key verifier is often denoted 'M2' and is provided in the
  /// server response to the client-generated session key verifier M1.
  Future<void> verifySession(List<int> serverSessionKeyVerifier) async {
    // M2 = H(A, M, K)
    final expectedServerSessionKeyVerifier = (await _hashAlgorithm.hash(
        _ephemeralUserPublicKeyBytes! + _userSessionKeyVerifier + sessionKey
    )).bytes;
    if (!serverSessionKeyVerifier.shallowEquals(expectedServerSessionKeyVerifier)) {
      throw AuthenticationFailure('Server session key failed verification.');
    }
    
    // Securely delete items no longer needed.
    _ephemeralUserPublicKeyBytes?.overwriteWithZeros();
    _ephemeralUserPublicKeyBytes = null;
    _userSessionKeyVerifier.overwriteWithZeros();
  }

  /// Private key.
  /// 
  /// RFC 5054 defines an unusual hash-based KDF:
  ///
  /// x = H(s, H( I | ‘:’ | p ))
  ///
  /// While fast, this KDF is not secure against brute-force extraction of the
  /// password from the verifier, and a stronger (i.e., slower) KDF is
  /// recommended.
  static Future<BigInt> _derivePrivateKey({
      required String password,
      required List<int> salt, required KdfAlgorithm kdfAlgorithm,
      String? userId,
  }) async {
    final privateKey = await kdfAlgorithm.deriveKeyFromPassword(
      password: userId != null ? '$userId:$password' : password,
      nonce: salt,
    );
    final privateKeyBytes = await privateKey.extractBytes();
    return privateKeyBytes.toBigInt();
  }

  /// Password verifier, a.k.a. verification key.
  /// v = g^x
  static BigInt _deriveVerificationKey({
      required BigInt privateKey,
      required BigInt generator, required BigInt safePrime,
  }) {
    final saltedVerificationKey = generator.modPow(privateKey, safePrime);
    return saltedVerificationKey;
  }

  /// Calculates the session key which will later be used for encrypted communication with server.
  ///
  /// K = H( (B - kg^x) ^ (a + ux) ) = H( (B - kv) ^ (a + ux) )
  Future<List<int>> _deriveSessionKey(
      List<int> salt, List<int> serverPublicKeyBytes) async {
    // x
    final privateKey = await _derivePrivateKey(
      userId: useUserIdInPrivateKey ? _userId : null,
      password: _password!,
      salt: _verifierKeySalt,
      kdfAlgorithm: _kdfAlgorithm,
    );
    //TODO: Erase no longer needed verifier key. After Uint8 switch.
    // _verifierKeySalt.overwriteWithZeros();
    // User credentials no longer needed, discard immediately.
    // 
    // FIXME: Store sensitive strings like password and user ID in a class that
    // supports replacement and/or immediate deletion. Uint8List seems to be the
    // suggested approach.
    _password = null;
    // v = g^x
    final verifierKey = _deriveVerificationKey(
      privateKey: privateKey,
      generator: generator, safePrime: safePrime
    );
    // u = H(A,B)
    final randomScramblingParameter = (await _hashRfc5054(
        [_ephemeralUserPublicKeyBytes!, serverPublicKeyBytes]
    )).toBigInt();
    if (randomScramblingParameter == BigInt.zero) {
      throw 'Abort authentication! Random scrambling parameter (u = H(A,B)) is zero.';
    }
    // k = H(N,g)
    final multiplierParameter = (await _hashRfc5054(
        [safePrime.toByteList(), generator.toByteList()]
    )).toBigInt();
    // Notated 'B'.
    final serverPublicKey = serverPublicKeyBytes.toBigInt();
    if (serverPublicKey % safePrime == BigInt.zero) {
      throw 'Abort authentication! Ephemeral public server key is invalid (B % N == 0).';
    }
    // B - k(g^x) = B - kv
    final firstTerm = serverPublicKey - multiplierParameter * verifierKey;
    // a + ux
    final secondTerm = _ephemeralUserPrivateKey! + randomScramblingParameter * privateKey;
    //TODO: Erase after Uint8List conversion.
    _ephemeralUserPrivateKey = null;
    // S = (B - kv) ^ (a + ux)
    final secret = firstTerm.modPow(secondTerm, safePrime);
    // K = H( (B - kg^x) ^ (a + ux) ) = H( (B - kv) ^ (a + ux) ) = H(S)
    final sessionKey = (await _hashAlgorithm.hash(secret.toByteList())).bytes;
    return sessionKey;
  }

  /// Utility method to perform a RFC 5054 compliant hash with appropriate
  /// padding and concatenation.
  Future<List<int>> _hashRfc5054(List<List<int>> byteLists) async {
    //OPTIMIZE: Make this a class field.
    final safePrimeBytes = safePrime.toByteList();
    return hashRfc5054(
      byteLists: byteLists,
      safePrime: safePrimeBytes,
      hashAlgorithm: _hashAlgorithm
    );
  }
}
